import { test, expect } from '@playwright/test'
import axe from 'axe-core'

test('Your Name exposes the film knowledge scope and a fifty-question exam', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('目录作品搜索').fill('Your Name')
  await expect(dialog.locator('.catalog-item')).toHaveCount(1)
  await dialog.getByRole('button', { name: '进入题库：Your Name', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('你的名字。 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('制作知识')
  await expect(page.getByRole('dialog')).toContainText('不混用小说扩写')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '全部专区', exact: true }).click()
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('君の名は')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
})

test('Tokyo Ghoul opens season one while all three sequel entries remain planned', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('目录分段').selectOption('all')
  await dialog.getByLabel('目录作品搜索').fill('Tokyo Ghoul')
  await expect(dialog.locator('.catalog-item')).toHaveCount(4)
  await expect(dialog.getByRole('button', { name: /^进入题库：/ })).toHaveCount(1)
  for (const number of [54, 121, 195]) {
    await expect(dialog.locator(`[data-number="${number}"]`)).toContainText('待制作')
  }
  await dialog.getByRole('button', { name: '进入题库：Tokyo Ghoul', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('东京喰种 第一季 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 1–12 集')
  await expect(page.getByRole('dialog')).toContainText('不混用 √A')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '全部专区', exact: true }).click()
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('东京食尸鬼')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
})

test('Jujutsu Kaisen exposes season one without completing the sequel or film', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('目录分段').selectOption('all')
  await dialog.getByLabel('目录作品搜索').fill('Jujutsu Kaisen')
  await expect(dialog.locator('.catalog-item')).toHaveCount(3)
  await expect(dialog.getByRole('button', { name: /^进入题库：/ })).toHaveCount(1)
  for (const number of [111, 136]) {
    await expect(dialog.locator(`[data-number="${number}"]`)).toContainText('待制作')
  }
  await dialog.getByRole('button', { name: '进入题库：Jujutsu Kaisen', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('咒术回战 第一季 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 1–24 集')
  await expect(page.getByRole('dialog')).toContainText('不考第二季')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '全部专区', exact: true }).click()
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('咒术')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
})

test('Hunter x Hunter exposes the 2011 scope and a full exam from the catalog', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('目录作品搜索').fill('Hunter x Hunter')
  await expect(dialog.locator('.catalog-item')).toHaveCount(1)
  await dialog.getByRole('button', { name: '进入题库：Hunter x Hunter', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('全职猎人 2011版 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 1–148 集')
  await expect(page.getByRole('dialog')).toContainText('不混用 1999 年版')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '全部专区', exact: true }).click()
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('全职猎人')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
})

test('SAO opens both first-season arcs without marking sequels as complete', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('目录分段').selectOption('all')
  await dialog.getByLabel('目录作品搜索').fill('Sword Art Online')
  await expect(dialog.locator('.catalog-item')).toHaveCount(3)
  await expect(dialog.getByRole('button', { name: /^进入题库：/ })).toHaveCount(1)
  for (const number of [40, 149]) {
    await expect(dialog.locator(`[data-number="${number}"]`)).toContainText('待制作')
  }
  await dialog.getByRole('button', { name: '进入题库：Sword Art Online', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('刀剑神域 第一季 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 1–25 集')
  await expect(page.getByRole('dialog')).toContainText('艾恩葛朗特篇与妖精之舞篇')
  await expect(page.getByRole('dialog')).toContainText('不考 SAO II')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '全部专区', exact: true }).click()
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('刀剑')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
})

test('My Hero Academia exposes only season one with fifty illustrated exam questions', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('目录分段').selectOption('all')
  await dialog.getByLabel('目录作品搜索').fill('My Hero Academia')
  await expect(dialog.getByRole('button', { name: /^进入题库：/ })).toHaveCount(1)
  for (const number of [16, 25, 53, 110]) {
    await expect(dialog.locator(`[data-number="${number}"]`)).toContainText('待制作')
  }
  await dialog.getByRole('button', { name: '进入题库：My Hero Academia', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('我的英雄学院 第一季 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 1–13 集')
  await expect(page.getByRole('dialog')).toContainText('不考第二季')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '全部专区', exact: true }).click()
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('我英')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
})

test('catalog preserves all ten batches and only opens existing question banks', async ({ page }) => {
  await page.goto('/')
  const opener = page.getByRole('button', { name: '查看 200 条目制作目录', exact: true })
  await opener.click()
  const dialog = page.getByRole('dialog', { name: '动漫题库制作目录' })
  await expect(dialog.locator('.catalog-item')).toHaveCount(20)
  await expect(dialog.locator('.catalog-summary')).toContainText('15 / 200')
  await expect(dialog.locator('.catalog-summary')).toContainText('750 / 10,000')
  await expect(dialog.locator('.catalog-item').first()).toContainText('Attack on Titan')
  await expect(dialog.locator('.catalog-item').first().getByRole('button')).toHaveCount(1)
  for (let batch = 1; batch <= 10; batch++) {
    await dialog.getByLabel('目录分段').selectOption(String(batch))
    await expect(dialog.locator('.catalog-item')).toHaveCount(20)
    await expect(dialog.locator('.catalog-item').first()).toHaveAttribute('data-number', String((batch - 1) * 20 + 1))
    await expect(dialog.locator('.catalog-item').last()).toHaveAttribute('data-number', String(batch * 20))
  }
  await page.keyboard.press('Escape')
  await expect(opener).toBeFocused()
  await opener.click()
  await dialog.getByRole('button', { name: '进入题库：Attack on Titan', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('#exam-title')).toHaveText('进击的巨人 第一季 · 模拟考试')
  await expect(page.locator('#exam-title')).toBeFocused()
})

test('Titan season two opens its own exam without unlocking later seasons', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录作品搜索').fill('Attack on Titan')
  for (const number of [18, 20]) await expect(page.locator(`.catalog-item[data-number="${number}"]`)).toContainText('待制作')
  await page.getByRole('button', { name: '进入题库：Attack on Titan Season 2', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('进击的巨人 第二季 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 26–37 集')
})

test('catalog searches the selected scope without merging seasons or counting partial collections', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('目录作品搜索').fill('ＮＡＲＵＴＯ')
  await expect(dialog.locator('.catalog-item')).toHaveCount(2)
  await expect(dialog.getByRole('button', { name: /^进入题库：/ })).toHaveCount(1)
  await dialog.getByLabel('目录分段').selectOption('2')
  await expect(dialog.locator('.catalog-empty')).toBeVisible()
  await dialog.getByRole('button', { name: '重置目录筛选', exact: true }).click()
  await expect(dialog.getByLabel('目录作品搜索')).toBeFocused()
  await expect(dialog.locator('.catalog-item')).toHaveCount(20)
  await dialog.getByLabel('目录分段').selectOption('all')
  await dialog.getByLabel('目录作品搜索').fill('Re:Zero')
  await expect(dialog.locator('.catalog-item')).toHaveCount(3)
  await expect(dialog.getByRole('button', { name: /^进入题库：/ })).toHaveCount(0)
  await dialog.getByLabel('目录作品搜索').fill('Attack on Titan')
  await expect(dialog.getByRole('button', { name: /^进入题库：/ })).toHaveCount(2)
  await expect(dialog.locator('[data-number="1"]')).toContainText('第 1–25 集')
  await expect(dialog.locator('[data-number="13"]')).toContainText('第 26–37 集')
  await dialog.getByLabel('目录作品搜索').fill('鬼灭')
  await expect(dialog.getByRole('button', { name: '进入题库：Demon Slayer', exact: true })).toBeVisible()
})

test('catalog is usable and accessible at 320px with long titles and filters', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('2')
  await page.evaluate(() => document.fonts.ready)
  await page.addScriptTag({ content: axe.source })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(await page.locator('dialog').evaluate((dialog) => dialog.scrollWidth <= dialog.clientWidth)).toBe(true)
  const violations = await page.evaluate(async () => (await (window as typeof window & { axe: typeof axe }).axe.run(document, {
    runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag21aa'] },
  })).violations.map(({ id, nodes }) => ({ id, targets: nodes.map(({ target }) => target) })))
  expect(violations).toEqual([])
})

test('Brotherhood opens its own sourced bank without marking the 2003 adaptation complete', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('目录分段').selectOption('all')
  await dialog.getByLabel('目录作品搜索').fill('Fullmetal Alchemist')
  await expect(dialog.locator('.catalog-item')).toHaveCount(2)
  await expect(dialog.locator('[data-number="87"]')).toContainText('待制作')
  await expect(dialog.getByRole('button', { name: /^进入题库：/ })).toHaveCount(1)
  await dialog.getByRole('button', { name: '进入题库：Fullmetal Alchemist: Brotherhood', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('钢之炼金术师 Brotherhood · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('2009–2010')
  await expect(page.getByRole('dialog')).toContainText('不混用 2003 年动画')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '全部专区', exact: true }).click()
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('钢炼')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('.quiz-card h3')).toContainText(['钢之炼金术师 Brotherhood', '钢之炼金术师 Brotherhood', '钢之炼金术师 Brotherhood'])
})

test('One Punch Man opens season one without making season two playable', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('目录分段').selectOption('all')
  await dialog.getByLabel('目录作品搜索').fill('One Punch Man')
  await expect(dialog.locator('.catalog-item')).toHaveCount(2)
  await expect(dialog.locator('[data-number="56"]')).toContainText('待制作')
  await expect(dialog.getByRole('button', { name: /^进入题库：/ })).toHaveCount(1)
  await dialog.getByRole('button', { name: '进入题库：One Punch Man', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('一拳超人 第一季 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 1–12 集')
  await expect(page.getByRole('dialog')).toContainText('不考第二季')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '全部专区', exact: true }).click()
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('一拳')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
})
