import { test, expect } from '@playwright/test'
import axe from 'axe-core'

test('Spirited Away opens its own film bank without counting the Ghibli collection twice', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('3')
  const entry = page.locator('.catalog-item[data-number="44"]')
  await expect(entry).toContainText('50 / 50')
  await expect(entry).not.toContainText('待单独整理')
  await expect(page.locator('.catalog-item[data-number="60"]')).toContainText('50 / 50')
  await entry.getByRole('button', { name: '进入题库：Spirited Away', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('千与千寻 · 模拟考试')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('2001年动画电影')
  await expect(page.getByRole('dialog')).toContainText('不混入舞台版')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '进入专区：吉卜力电影', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('吉卜力电影 · 模拟考试')
})

test('Parasyte opens a complete TV bank with three levels and adaptation boundaries', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('3')
  const entry = page.locator('.catalog-item[data-number="43"]')
  await expect(entry).toContainText('50 / 50')
  await expect(page.locator('.catalog-item[data-number="60"]')).toContainText('50 / 50')
  await entry.getByRole('button', { name: '进入题库：Parasyte: The Maxim', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('寄生兽 生命的准则 · 模拟考试')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 1–24 集')
  await expect(page.getByRole('dialog')).toContainText('不混入真人电影')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Blue Exorcist opens the 2011 continuity and excludes Kyoto and later arcs', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('3')
  const entry = page.locator('.catalog-item[data-number="42"]')
  await expect(entry).toContainText('50 / 50')
  await expect(page.locator('.catalog-item[data-number="60"]')).toContainText('50 / 50')
  await entry.getByRole('button', { name: '进入题库：Blue Exorcist', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('青之驱魔师 第一季 · 模拟考试')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('2011年电视动画第一季第 1–25 集')
  await expect(page.getByRole('dialog')).toContainText('不混入京都不净王篇')
  await expect(page.getByRole('dialog')).toContainText('动画原创展开')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Cowboy Bebop opens the TV bank without the film or live-action adaptation', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('3')
  const entry = page.locator('.catalog-item[data-number="41"]')
  await expect(entry).toContainText('50 / 50')
  await expect(page.locator('.catalog-item[data-number="60"]')).toContainText('50 / 50')
  await entry.getByRole('button', { name: '进入题库：Cowboy Bebop', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('星际牛仔 · 模拟考试')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('电视动画第 1–26 集')
  await expect(page.getByRole('dialog')).toContainText('不混入剧场版')
  await expect(page.getByRole('dialog')).toContainText('红龙终局')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('SAO II opens its three arcs alongside the completed third batch', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('2')
  const entry = page.locator('.catalog-item[data-number="40"]')
  await expect(entry).toContainText('50 / 50')
  await expect(page.locator('.catalog-item').filter({ hasText: '50 / 50' })).toHaveCount(20)
  await page.getByLabel('目录分段').selectOption('3')
  await expect(page.locator('.catalog-item[data-number="60"]')).toContainText('50 / 50')
  await page.getByLabel('目录分段').selectOption('2')
  await entry.getByRole('button', { name: '进入题库：Sword Art Online II', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('刀剑神域Ⅱ · 模拟考试')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第二季第 1–24 集')
  await expect(page.getByRole('dialog')).toContainText('不含14.5集总集篇')
  await expect(page.getByRole('dialog')).toContainText('圣母圣咏')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Future Diary opens its TV bank without Redial or live-action content', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('2')
  const entry = page.locator('.catalog-item[data-number="39"]')
  await expect(entry).toContainText('50 / 50')
  await expect(page.locator('.catalog-item[data-number="40"]')).toContainText('50 / 50')
  await entry.getByRole('button', { name: '进入题库：The Future Diary', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('未来日记 · 模拟考试')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('正篇第 1–26 集')
  await expect(page.getByRole('dialog')).toContainText('不混入Redial')
  await expect(page.getByRole('dialog')).toContainText('世界重启')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('KonoSuba opens its first-season bank with skill and adaptation scope', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('2')
  const entry = page.locator('.catalog-item[data-number="38"]')
  await expect(entry).toContainText('50 / 50')
  await expect(page.locator('.catalog-item[data-number="40"]')).toContainText('50 / 50')
  await entry.getByRole('button', { name: "进入题库：KonoSuba: God's Blessing on This Wonderful World!", exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('为美好的世界献上祝福！ 第一季 · 模拟考试')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第一季第 1–10 集')
  await expect(page.getByRole('dialog')).toContainText('不混入第二季')
  await expect(page.getByRole('dialog')).toContainText('机动要塞战')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Promised Neverland opens its first-season fifty-question bank', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('2')
  const entry = page.locator('.catalog-item[data-number="37"]')
  await expect(entry).toContainText('50 / 50')
  await expect(page.locator('.catalog-item[data-number="40"]')).toContainText('50 / 50')
  await entry.getByRole('button', { name: '进入题库：The Promised Neverland', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('约定的梦幻岛 第一季 · 模拟考试')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第一季第 1–12 集')
  await expect(page.getByRole('dialog')).toContainText('不混入第二季')
  await expect(page.getByRole('dialog')).toContainText('逃脱结局')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Haikyuu opens season one with fifty questions and later adaptations excluded', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('2')
  const entry = page.locator('.catalog-item[data-number="36"]')
  await expect(entry).toContainText('50 / 50')
  await expect(page.locator('.catalog-item[data-number="40"]')).toContainText('50 / 50')
  await entry.getByRole('button', { name: '进入题库：Haikyuu!!', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('排球少年 第一季 · 模拟考试')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第一季第 1–25 集')
  await expect(page.getByRole('dialog')).toContainText('不混入第二季')
  await expect(page.getByRole('dialog')).toContainText('预选赛对阵')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Angel Beats opens its TV bank with special and game exclusions', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('2')
  const entry = page.locator('.catalog-item[data-number="35"]')
  await expect(entry).toContainText('50 / 50')
  await expect(page.locator('.catalog-item[data-number="40"]')).toContainText('50 / 50')
  await entry.getByRole('button', { name: '进入题库：Angel Beats!', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('Angel Beats! · 模拟考试')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 1–13 集')
  await expect(page.getByRole('dialog')).toContainText('不混入特别篇')
  await expect(page.getByRole('dialog')).toContainText('毕业式剧透')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Seven Deadly Sins opens its first-season bank with sequel exclusions', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('2')
  const entry = page.locator('.catalog-item[data-number="34"]')
  await expect(entry).toContainText('50 / 50')
  await expect(page.locator('.catalog-item[data-number="40"]')).toContainText('50 / 50')
  await entry.getByRole('button', { name: '进入题库：The Seven Deadly Sins', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('七大罪 第一季 · 模拟考试')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第一季第 1–24 集')
  await expect(page.getByRole('dialog')).toContainText('不混入戒律的复活')
  await expect(page.getByRole('dialog')).toContainText('亨德里克森相关剧透')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Assassination Classroom opens season one without unlocking season two', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('all')
  await page.getByLabel('目录作品搜索').fill('Assassination Classroom')
  await expect(page.locator('.catalog-item[data-number="84"]')).toContainText('待制作')
  const entry = page.locator('.catalog-item[data-number="33"]')
  await expect(entry).toContainText('50 / 50')
  await entry.getByRole('button', { name: '进入题库：Assassination Classroom', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('暗杀教室 第一季 · 模拟考试')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第一季第 1–22 集')
  await expect(page.getByRole('dialog')).toContainText('不混入第二季')
  await expect(page.getByRole('dialog')).toContainText('海岛救援')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Bleach opens the Substitute Soul Reaper arc with fifty questions', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('2')
  const entry = page.locator('.catalog-item[data-number="32"]')
  await expect(entry).toContainText('50 / 50')
  await expect(page.locator('.catalog-item[data-number="40"]')).toContainText('50 / 50')
  await entry.getByRole('button', { name: '进入题库：Bleach', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('死神 死神代行篇 · 模拟考试')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 1–20 集')
  await expect(page.getByRole('dialog')).toContainText('不混入千年血战篇')
  await expect(page.getByRole('dialog')).toContainText('救援训练剧透')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Akame opens fifty illustrated TV questions with adaptation boundaries', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('2')
  const entry = page.locator('.catalog-item[data-number="31"]')
  await expect(entry).toContainText('50 / 50')
  await expect(page.locator('.catalog-item[data-number="40"]')).toContainText('50 / 50')
  await entry.getByRole('button', { name: '进入题库：Akame ga Kill!', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('斩！赤红之瞳 · 模拟考试')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 1–24 集')
  await expect(page.getByRole('dialog')).toContainText('人物命运剧透')
  await expect(page.getByRole('dialog')).toContainText('不混入漫画')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Erased opens its complete TV bank with spoiler scope on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('2')
  const entry = page.locator('.catalog-item[data-number="30"]')
  await expect(entry).toContainText('50 / 50')
  await entry.getByRole('button', { name: '进入题库：Erased', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('只有我不在的街道 · 模拟考试')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 1–12 集')
  await expect(page.getByRole('dialog')).toContainText('真凶与结局剧透')
  await expect(page.getByRole('dialog')).toContainText('不混入真人电影')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Titan Final Season opens part one with production scope and leaves Part 2 planned', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('all')
  await page.getByLabel('目录作品搜索').fill('Attack on Titan: The Final Season')
  await expect(page.locator('.catalog-item[data-number="92"]')).toContainText('待制作')
  const entry = page.locator('.catalog-item[data-number="29"]')
  await expect(entry).toContainText('50 / 50')
  await entry.getByRole('button', { name: '进入题库：Attack on Titan: The Final Season', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('进击的巨人 最终季前半部 · 模拟考试')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 60–75 集')
  await expect(page.getByRole('dialog')).toContainText('制作资料')
  await expect(page.getByRole('dialog')).toContainText('不混入Part 2')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Noragami opens season one while Aragoto remains planned', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('all')
  await page.getByLabel('目录作品搜索').fill('Noragami')
  await expect(page.locator('.catalog-item[data-number="88"]')).toContainText('待制作')
  const entry = page.locator('.catalog-item[data-number="28"]')
  await expect(entry).toContainText('50 / 50')
  await entry.getByRole('button', { name: '进入题库：Noragami', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('野良神 第一季 · 模拟考试')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第一季第 1–12 集')
  await expect(page.getByRole('dialog')).toContainText('不混入Aragoto第二季')
  await expect(page.getByRole('dialog')).toContainText('动画原创角色')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Mob Psycho keeps season one separate from its completed sequel', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('all')
  await page.getByLabel('目录作品搜索').fill('Mob Psycho')
  await expect(page.locator('.catalog-item[data-number="73"]')).toContainText('50 / 50')
  const entry = page.locator('.catalog-item[data-number="27"]')
  await expect(entry).toContainText('50 / 50')
  await entry.getByRole('button', { name: '进入题库：Mob Psycho 100', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('灵能百分百 第一季 · 模拟考试')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第一季第 1–12 集')
  await expect(page.getByRole('dialog')).toContainText('不混入第二季')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Toradora opens its TV bank with three practices and a fifty-question exam', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('2')
  const entry = page.locator('.catalog-item[data-number="26"]')
  await expect(entry).toContainText('50 / 50')
  await entry.getByRole('button', { name: '进入题库：Toradora!', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('龙与虎 · 模拟考试')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 1–25 集')
  await expect(page.getByRole('dialog')).toContainText('不混入小说、游戏或OVA')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Hero season three opens separately with its TV special exclusion', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('2')
  const entry = page.locator('.catalog-item[data-number="25"]')
  await expect(entry).toContainText('50 / 50')
  await entry.getByRole('button', { name: '进入题库：My Hero Academia 3rd Season', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('我的英雄学院 第三季 · 模拟考试')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 39–63 集')
  await expect(page.getByRole('dialog')).toContainText('不含第58集')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Your Lie in April opens three practices and a scoped 50-question TV exam', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('2')
  const entry = page.locator('.catalog-item[data-number="24"]')
  await expect(entry).toContainText('50 / 50')
  await entry.getByRole('button', { name: '进入题库：Your Lie in April', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('四月是你的谎言 · 模拟考试')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 1–22 集')
  await expect(page.getByRole('dialog')).toContainText('不混入第23话OAD')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Re:Zero season one opens independently while later seasons remain planned', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await expect(page.getByRole('button', { name: '进入专区：Re:0', exact: true })).toContainText('前两季综合')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('all')
  await page.getByLabel('目录作品搜索').fill('Re:Zero')
  for (const number of [128, 173]) await expect(page.locator(`.catalog-item[data-number="${number}"]`)).toContainText('待制作')
  await page.getByRole('button', { name: '进入题库：Re:Zero - Starting Life in Another World', exact: true }).click()
  const setup = page.locator('.exam-setup')
  await expect(page.locator('#exam-title')).toHaveText('Re:0 第一季 · 模拟考试')
  await setup.getByText('考试范围与剧透说明', { exact: true }).click()
  await expect(setup.locator('.exam-scope p')).toBeVisible()
  await expect(setup.locator('.exam-scope p')).toContainText('不混入第二季')
  await setup.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await setup.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第一季第 1–25 集')
  await expect(page.getByRole('dialog')).toContainText('Memory Snow')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Code Geass preserves season one separately from the completed R2 bank', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('all')
  await page.getByLabel('目录作品搜索').fill('Code Geass')
  const items = page.locator('.catalog-item')
  await expect(items).toHaveCount(2)
  await expect(items.filter({ has: page.getByRole('heading', { name: 'Code Geass: Lelouch of the Rebellion R2', exact: true }) })).toContainText('50 / 50')
  await page.getByRole('button', { name: '进入题库：Code Geass: Lelouch of the Rebellion', exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第一季第 1–25 集')
  await expect(page.getByRole('dialog')).toContainText('不混入R2')
})

test('No Game No Life opens a TV-only bank from batch two with searchable game mechanics', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '动漫题库制作目录' })
  await dialog.getByLabel('目录分段').selectOption('2')
  const entry = dialog.locator('.catalog-item[data-number="21"]')
  await expect(entry).toContainText('50 / 50')
  await expect(entry).toContainText('2014 年电视动画第 1–12 集')
  await expect(entry).toContainText('不混入 Zero')
  await entry.getByRole('button', { name: '进入题库：No Game No Life', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('游戏人生 · 模拟考试')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('血坏')
  await expect(page.locator('.quiz-card')).not.toHaveCount(0)
  await page.getByRole('button', { name: '清空搜索', exact: true }).click()
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.locator('.quiz-rules')).toContainText('50 道单选题')
  await expect(page.getByRole('dialog')).toContainText('2014 年电视动画第 1–12 集')
  await expect(page.getByRole('dialog')).toContainText('不混入 Zero')
})

test('Titan season three part two stays separate from Final Season Part 2', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await expect(page.locator('.catalog-item button')).toHaveCount(20)
  await page.getByLabel('目录分段').selectOption('all')
  await page.getByLabel('目录作品搜索').fill('Attack on Titan')
  for (const number of [92]) await expect(page.locator(`.catalog-item[data-number="${number}"]`)).toContainText('待制作')
  await page.getByRole('button', { name: '进入题库：Attack on Titan Season 3 Part 2', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('进击的巨人 第三季后半部 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 50–59 集')
  await expect(page.getByRole('dialog')).toContainText('制作知识')
  await expect(page.getByRole('dialog')).toContainText('不混入最终季')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('A Silent Voice exposes its film and sound-design scope with multilingual discovery', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录作品搜索').fill('A Silent Voice')
  await page.getByRole('button', { name: '进入题库：A Silent Voice', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('声之形 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('2016 年动画电影')
  await expect(page.getByRole('dialog')).toContainText('电影声音设计')
  await expect(page.getByRole('dialog')).toContainText('不混用漫画独有情节')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '全部专区', exact: true }).click()
  for (const alias of ['声之形', '聲の形', 'a silent voice']) {
    await page.getByRole('textbox', { name: '搜索 Quiz' }).fill(alias)
    await expect(page.locator('.quiz-card')).toHaveCount(3)
  }
})

test('Your Name exposes the film knowledge scope and a fifty-question exam', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('目录作品搜索').fill('Your Name')
  await expect(dialog.locator('.catalog-item')).toHaveCount(1)
  await dialog.getByRole('button', { name: '进入题库：Your Name', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('你的名字。 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('制作知识')
  await expect(page.getByRole('dialog')).toContainText('不混用小说扩写')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '全部专区', exact: true }).click()
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('君の名は')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
})

test('Tokyo Ghoul opens season one while both re sequel entries remain planned', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('目录分段').selectOption('all')
  await dialog.getByLabel('目录作品搜索').fill('Tokyo Ghoul')
  await expect(dialog.locator('.catalog-item')).toHaveCount(4)
  await expect(dialog.getByRole('button', { name: /^进入题库：/ })).toHaveCount(2)
  for (const number of [121, 195]) {
    await expect(dialog.locator(`[data-number="${number}"]`)).toContainText('待制作')
  }
  await dialog.getByRole('button', { name: '进入题库：Tokyo Ghoul', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('东京喰种 第一季 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 1–12 集')
  await expect(page.getByRole('dialog')).toContainText('不混用 √A')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '全部专区', exact: true }).click()
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('东京食尸鬼')
  await expect(page.locator('.quiz-card')).toHaveCount(6)
})

test('Jujutsu Kaisen exposes season one without completing the sequel or film', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('目录分段').selectOption('all')
  await dialog.getByLabel('目录作品搜索').fill('Jujutsu Kaisen')
  await expect(dialog.locator('.catalog-item')).toHaveCount(3)
  await expect(dialog.getByRole('button', { name: /^进入题库：/ })).toHaveCount(1)
  for (const number of [111, 136]) {
    await expect(dialog.locator(`[data-number="${number}"]`)).toContainText('待制作')
  }
  await dialog.getByRole('button', { name: '进入题库：Jujutsu Kaisen', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('咒术回战 第一季 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 1–24 集')
  await expect(page.getByRole('dialog')).toContainText('不考第二季')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '全部专区', exact: true }).click()
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('咒术')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
})

test('Hunter x Hunter exposes the 2011 scope and a full exam from the catalog', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('目录作品搜索').fill('Hunter x Hunter')
  await expect(dialog.locator('.catalog-item')).toHaveCount(1)
  await dialog.getByRole('button', { name: '进入题库：Hunter x Hunter', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('全职猎人 2011版 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 1–148 集')
  await expect(page.getByRole('dialog')).toContainText('不混用 1999 年版')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '全部专区', exact: true }).click()
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('全职猎人')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
})

test('SAO keeps the first season separate from SAO II and the planned Alicization bank', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('目录分段').selectOption('all')
  await dialog.getByLabel('目录作品搜索').fill('Sword Art Online')
  await expect(dialog.locator('.catalog-item')).toHaveCount(3)
  await expect(dialog.getByRole('button', { name: /^进入题库：/ })).toHaveCount(2)
  for (const number of [149]) {
    await expect(dialog.locator(`[data-number="${number}"]`)).toContainText('待制作')
  }
  await dialog.getByRole('button', { name: '进入题库：Sword Art Online', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('刀剑神域 第一季 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 1–25 集')
  await expect(page.getByRole('dialog')).toContainText('艾恩葛朗特篇与妖精之舞篇')
  await expect(page.getByRole('dialog')).toContainText('不考 SAO II')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '全部专区', exact: true }).click()
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('刀剑')
  await expect(page.locator('.quiz-card')).toHaveCount(6)
})

test('My Hero Academia preserves season one with fifty illustrated exam questions', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('目录分段').selectOption('all')
  await dialog.getByLabel('目录作品搜索').fill('My Hero Academia')
  await expect(dialog.getByRole('button', { name: /^进入题库：/ })).toHaveCount(4)
  await expect(dialog.locator('[data-number="25"]')).toContainText('50 / 50')
  for (const number of [110]) {
    await expect(dialog.locator(`[data-number="${number}"]`)).toContainText('待制作')
  }
  await dialog.getByRole('button', { name: '进入题库：My Hero Academia', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('我的英雄学院 第一季 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 1–13 集')
  await expect(page.getByRole('dialog')).toContainText('不考第二季')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '全部专区', exact: true }).click()
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('我英')
  await expect(page.locator('.quiz-card')).toHaveCount(12)
})

test('catalog preserves all ten batches and only opens existing question banks', async ({ page }) => {
  await page.goto('/')
  const opener = page.getByRole('button', { name: '查看 200 条目制作目录', exact: true })
  await opener.click()
  const dialog = page.getByRole('dialog', { name: '动漫题库制作目录' })
  await expect(dialog.locator('.catalog-item')).toHaveCount(20)
  await expect(dialog.locator('.catalog-summary')).toContainText('74 / 200')
  await expect(dialog.locator('.catalog-summary')).toContainText('3,700 / 10,000')
  await expect(dialog.locator('.catalog-item').first()).toContainText('Attack on Titan')
  await expect(dialog.locator('.catalog-item').first().getByRole('button')).toHaveCount(1)
  for (let batch = 1; batch <= 10; batch++) {
    await dialog.getByLabel('目录分段').selectOption(String(batch))
    await expect(dialog.locator('.catalog-item')).toHaveCount(20)
    await expect(dialog.locator('.catalog-item').first()).toHaveAttribute('data-number', String((batch - 1) * 20 + 1))
    await expect(dialog.locator('.catalog-item').last()).toHaveAttribute('data-number', String(batch * 20))
  }
  await page.keyboard.press('Escape')
  await expect(opener).toBeFocused()
  await opener.click()
  await dialog.getByRole('button', { name: '进入题库：Attack on Titan', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('#exam-title')).toHaveText('进击的巨人 第一季 · 模拟考试')
  await expect(page.locator('#exam-title')).toBeFocused()
})

test('Titan season three part one stays separate from part two', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录作品搜索').fill('Attack on Titan')
  await expect(page.getByRole('button', { name: '进入题库：Attack on Titan Season 3 Part 2', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '进入题库：Attack on Titan Season 3', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('进击的巨人 第三季上半部 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 38–49 集')
  await expect(page.getByRole('dialog')).toContainText('不混用第50集起')
})

test('Hero Academia season two opens its own fifty-question exam', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录作品搜索').fill('My Hero Academia')
  await page.getByRole('button', { name: '进入题库：My Hero Academia 2nd Season', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('我的英雄学院 第二季 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 14–38 集')
  await expect(page.getByRole('dialog')).toContainText('期末实技考试')
})

test('Shippuden opens a separate Kazekage rescue exam with an explicit arc scope', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录作品搜索').fill('Naruto')
  await expect(page.getByRole('button', { name: /^进入题库：/ })).toHaveCount(2)
  await page.getByRole('button', { name: '进入题库：Naruto: Shippuden', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('火影忍者 疾风传 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 1–32 集风影夺还篇')
  await expect(page.getByRole('dialog')).toContainText('不代表全部疾风传')
})

test('Steins Gate opens the 2011 TV exam without completing its other adaptations', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('all')
  await page.getByLabel('目录作品搜索').fill('Steins')
  await expect(page.getByRole('button', { name: /^进入题库：/ })).toHaveCount(1)
  await page.getByRole('button', { name: '进入题库：Steins;Gate', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('命运石之门 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 1–24 集')
  await expect(page.getByRole('dialog')).toContainText('不混用命运石之门 0')
})

test('Titan season two opens its own exam alongside separately available later seasons', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录作品搜索').fill('Attack on Titan')
  await expect(page.getByRole('button', { name: /^进入题库：/ })).toHaveCount(4)
  await page.getByRole('button', { name: '进入题库：Attack on Titan Season 2', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('进击的巨人 第二季 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 26–37 集')
})

test('catalog searches the selected scope without merging seasons or counting partial collections', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('目录作品搜索').fill('ＮＡＲＵＴＯ')
  await expect(dialog.locator('.catalog-item')).toHaveCount(2)
  await expect(dialog.getByRole('button', { name: /^进入题库：/ })).toHaveCount(2)
  await dialog.getByLabel('目录分段').selectOption('2')
  await expect(dialog.locator('.catalog-empty')).toBeVisible()
  await dialog.getByRole('button', { name: '重置目录筛选', exact: true }).click()
  await expect(dialog.getByLabel('目录作品搜索')).toBeFocused()
  await expect(dialog.locator('.catalog-item')).toHaveCount(20)
  await dialog.getByLabel('目录分段').selectOption('all')
  await dialog.getByLabel('目录作品搜索').fill('Re:Zero')
  await expect(dialog.locator('.catalog-item')).toHaveCount(3)
  await expect(dialog.getByRole('button', { name: /^进入题库：/ })).toHaveCount(1)
  await dialog.getByLabel('目录作品搜索').fill('Attack on Titan')
  await expect(dialog.getByRole('button', { name: /^进入题库：/ })).toHaveCount(5)
  await expect(dialog.locator('[data-number="1"]')).toContainText('第 1–25 集')
  await expect(dialog.locator('[data-number="13"]')).toContainText('第 26–37 集')
  await expect(dialog.locator('[data-number="29"]')).toContainText('第 60–75 集')
  await expect(dialog.locator('[data-number="92"]')).toContainText('待制作')
  await dialog.getByLabel('目录作品搜索').fill('鬼灭')
  await expect(dialog.getByRole('button', { name: '进入题库：Demon Slayer', exact: true })).toBeVisible()
})

test('catalog is usable and accessible at 320px with long titles and filters', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('2')
  await page.evaluate(() => document.fonts.ready)
  await page.addScriptTag({ content: axe.source })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(await page.locator('dialog').evaluate((dialog) => dialog.scrollWidth <= dialog.clientWidth)).toBe(true)
  const violations = await page.evaluate(async () => (await (window as typeof window & { axe: typeof axe }).axe.run(document, {
    runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag21aa'] },
  })).violations.map(({ id, nodes }) => ({ id, targets: nodes.map(({ target }) => target) })))
  expect(violations).toEqual([])
})

test('Brotherhood opens its own sourced bank without marking the 2003 adaptation complete', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('目录分段').selectOption('all')
  await dialog.getByLabel('目录作品搜索').fill('Fullmetal Alchemist')
  await expect(dialog.locator('.catalog-item')).toHaveCount(2)
  await expect(dialog.locator('[data-number="87"]')).toContainText('待制作')
  await expect(dialog.getByRole('button', { name: /^进入题库：/ })).toHaveCount(1)
  await dialog.getByRole('button', { name: '进入题库：Fullmetal Alchemist: Brotherhood', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('钢之炼金术师 Brotherhood · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('2009–2010')
  await expect(page.getByRole('dialog')).toContainText('不混用 2003 年动画')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '全部专区', exact: true }).click()
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('钢炼')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('.quiz-card h3')).toContainText(['钢之炼金术师 Brotherhood', '钢之炼金术师 Brotherhood', '钢之炼金术师 Brotherhood'])
})

test('One Punch Man opens season one separately from its completed second season', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('目录分段').selectOption('all')
  await dialog.getByLabel('目录作品搜索').fill('One Punch Man')
  await expect(dialog.locator('.catalog-item')).toHaveCount(2)
  await expect(dialog.locator('[data-number="56"]')).toContainText('50 / 50')
  await expect(dialog.getByRole('button', { name: /^进入题库：/ })).toHaveCount(2)
  await dialog.getByRole('button', { name: '进入题库：One Punch Man', exact: true }).click()
  await expect(page.locator('#exam-title')).toHaveText('一拳超人 第一季 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 1–12 集')
  await expect(page.getByRole('dialog')).toContainText('不考第二季')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '全部专区', exact: true }).click()
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('一拳')
  await expect(page.locator('.quiz-card')).toHaveCount(6)
})


test('evangelion TV bank opens fifty illustrated questions on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('3')
  await expect(page.locator('.catalog-item[data-number="45"]')).toContainText('50 / 50')
  await page.getByRole('button', { name: '进入题库：Neon Genesis Evangelion', exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('#exam-title')).toHaveText('新世纪福音战士 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('电视系列第 1–26 集')
  await expect(page.getByRole('dialog')).toContainText('不混入旧剧场版、新剧场版')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('violet-evergarden TV bank opens fifty illustrated questions on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('3')
  await expect(page.locator('.catalog-item[data-number="46"]')).toContainText('50 / 50')
  await page.getByRole('button', { name: '进入题库：Violet Evergarden', exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('#exam-title')).toHaveText('紫罗兰永恒花园 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('电视动画第 1–13 集')
  await expect(page.getByRole('dialog')).toContainText('不混入番外篇、外传电影和剧场版')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('code-geass-r2 TV bank opens fifty illustrated questions on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('3')
  await expect(page.locator('.catalog-item[data-number="47"]')).toContainText('50 / 50')
  await page.getByRole('button', { name: '进入题库：Code Geass: Lelouch of the Rebellion R2', exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('#exam-title')).toHaveText('反叛的鲁路修 R2 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('R2第 1–25 集')
  await expect(page.getByRole('dialog')).toContainText('不混入总集篇电影及《复活的鲁路修》')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('bunny-girl-senpai TV bank opens fifty illustrated questions on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('3')
  await expect(page.locator('.catalog-item[data-number="48"]')).toContainText('50 / 50')
  await page.getByRole('button', { name: '进入题库：Rascal Does Not Dream of Bunny Girl Senpai', exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('#exam-title')).toHaveText('青春猪头少年不会梦到兔女郎学姐 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('2018年电视动画第 1–13 集')
  await expect(page.getByRole('dialog')).toContainText('不混入后续电影及大学篇')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('dr-stone season one bank opens fifty illustrated questions on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('3')
  await expect(page.locator('.catalog-item[data-number="49"]')).toContainText('50 / 50')
  await page.getByRole('button', { name: '进入题库：Dr. Stone', exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('#exam-title')).toHaveText('石纪元 第一季 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第一季第 1–24 集')
  await expect(page.getByRole('dialog')).toContainText('不混入STONE WARS、龙水及后续季度')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('kaguya-sama season one bank opens fifty illustrated questions on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('3')
  await expect(page.locator('.catalog-item[data-number="50"]')).toContainText('50 / 50')
  await page.getByRole('button', { name: '进入题库：Kaguya-sama: Love is War', exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('#exam-title')).toHaveText('辉夜大小姐想让我告白 第一季 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('2019年电视动画第一季第 1–12 集')
  await expect(page.getByRole('dialog')).toContainText('不混入后续季度、电影或漫画后续')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('chainsaw-man TV bank opens fifty illustrated questions on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('3')
  await expect(page.locator('.catalog-item[data-number="51"]')).toContainText('50 / 50')
  await page.getByRole('button', { name: '进入题库：Chainsaw Man', exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('#exam-title')).toHaveText('电锯人 第一季 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('2022年电视动画第 1–12 集')
  await expect(page.getByRole('dialog')).toContainText('不混入总集篇、蕾塞篇及后续剧情')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('death-parade TV bank opens fifty illustrated questions on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('3')
  await expect(page.locator('.catalog-item[data-number="52"]')).toContainText('50 / 50')
  await page.getByRole('button', { name: '进入题库：Death Parade', exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('#exam-title')).toHaveText('死亡游行 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('2015年电视动画第 1–12 集')
  await expect(page.getByRole('dialog')).toContainText('不混入前作短片《死亡台球》')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('my-hero-academia-season-4 TV bank opens fifty illustrated questions on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('3')
  await expect(page.locator('.catalog-item[data-number="53"]')).toContainText('50 / 50')
  await page.getByRole('button', { name: '进入题库：My Hero Academia 4th Season', exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('#exam-title')).toHaveText('我的英雄学院 第四季 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第四季第 1–25 集')
  await expect(page.getByRole('dialog')).toContainText('不混入其他季度、电影或OVA')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('tokyo-ghoul-root-a TV bank opens fifty illustrated questions on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('3')
  await expect(page.locator('.catalog-item[data-number="54"]')).toContainText('50 / 50')
  await page.getByRole('button', { name: '进入题库：Tokyo Ghoul √A', exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('#exam-title')).toHaveText('东京喰种√A · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第二季√A第 1–12 集')
  await expect(page.getByRole('dialog')).toContainText('不混入漫画独有剧情、:re、OVA或真人版')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('black-clover TV bank opens fifty illustrated questions on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('3')
  await expect(page.locator('.catalog-item[data-number="55"]')).toContainText('50 / 50')
  await page.getByRole('button', { name: '进入题库：Black Clover', exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('#exam-title')).toHaveText('黑色四叶草 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 1–51 集')
  await expect(page.getByRole('dialog')).toContainText('不代表全篇覆盖')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('one-punch-man-season-2 TV bank opens fifty illustrated questions on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('3')
  await expect(page.locator('.catalog-item[data-number="56"]')).toContainText('50 / 50')
  await page.getByRole('button', { name: '进入题库：One Punch Man Season 2', exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('#exam-title')).toHaveText('一拳超人 第二季 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第二季第 1–12 集')
  await expect(page.getByRole('dialog')).toContainText('不混入第三季、OVA或漫画后续')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('spy-family TV bank opens fifty illustrated questions on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('3')
  await expect(page.locator('.catalog-item[data-number="57"]')).toContainText('50 / 50')
  await page.getByRole('button', { name: '进入题库：Spy x Family', exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('#exam-title')).toHaveText('间谍过家家 第一季前半部 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('前半部第 1–12 集')
  await expect(page.getByRole('dialog')).toContainText('不混入Part 2、后续季度、电影或漫画后续')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})


test('Spy x Family keeps Part 2 planned and searches Part 1 by Chinese alias', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('目录分段').selectOption('all')
  await dialog.getByLabel('目录作品搜索').fill('Spy x Family')
  await expect(dialog.locator('.catalog-item')).toHaveCount(2)
  await expect(dialog.locator('[data-number="157"]')).toContainText('待制作')
  await expect(dialog.getByRole('button', { name: /^进入题库：/ })).toHaveCount(1)
  await dialog.getByRole('button', { name: '关闭', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('间谍家家酒')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
})

test('kill-la-kill TV bank opens fifty illustrated questions on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('3')
  await expect(page.locator('.catalog-item[data-number="58"]')).toContainText('50 / 50')
  await page.getByRole('button', { name: '进入题库：Kill la Kill', exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('#exam-title')).toHaveText('斩服少女 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('电视动画第 1–24 集')
  await expect(page.getByRole('dialog')).toContainText('不混入第25集番外或漫画改编')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('fairy-tail TV bank opens fifty illustrated questions on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('3')
  await expect(page.locator('.catalog-item[data-number="59"]')).toContainText('50 / 50')
  await page.getByRole('button', { name: '进入题库：Fairy Tail', exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('#exam-title')).toHaveText('妖精的尾巴 初期篇 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('电视动画第 1–48 集')
  await expect(page.getByRole('dialog')).toContainText('不混入2014版')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Fairy Tail keeps the 2014 sequel planned', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('目录分段').selectOption('all')
  await dialog.getByLabel('目录作品搜索').fill('Fairy Tail')
  await expect(dialog.locator('.catalog-item')).toHaveCount(2)
  await expect(dialog.locator('[data-number="169"]')).toContainText('待制作')
  await expect(dialog.getByRole('button', { name: /^进入题库：/ })).toHaveCount(1)
})

test('jojo-2012 TV bank opens fifty illustrated questions on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('3')
  await expect(page.locator('.catalog-item[data-number="60"]')).toContainText('50 / 50')
  await page.getByRole('button', { name: "进入题库：JoJo's Bizarre Adventure", exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('#exam-title')).toHaveText('JOJO的奇妙冒险 2012版 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('电视动画第 1–26 集')
  await expect(page.getByRole('dialog')).toContainText('不混入星尘斗士')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})


test('JoJo completes batch three while later JoJo arcs and the next unfinished entry stay planned', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('目录分段').selectOption('3')
  await expect(dialog.locator('.catalog-item').filter({ hasText: '50 / 50' })).toHaveCount(20)
  await dialog.getByLabel('目录分段').selectOption('4')
  await expect(dialog.locator('[data-number="74"]')).toContainText('待制作')
  await dialog.getByLabel('目录分段').selectOption('all')
  await dialog.getByLabel('目录作品搜索').fill('JoJo')
  await expect(dialog.locator('.catalog-item')).toHaveCount(5)
  for (const number of [108, 129, 133, 146]) {
    await expect(dialog.locator(`[data-number="${number}"]`)).toContainText('待制作')
  }
  await expect(dialog.getByRole('button', { name: /^进入题库：/ })).toHaveCount(1)
})

test('darling-in-the-franxx TV bank opens fifty illustrated questions on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('4')
  await expect(page.locator('.catalog-item[data-number="61"]')).toContainText('50 / 50')
  await page.getByRole('button', { name: "进入题库：Darling in the FranXX", exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('#exam-title')).toHaveText('DARLING in the FRANXX · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('电视动画第 1–24 集')
  await expect(page.getByRole('dialog')).toContainText('不混入漫画改编')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Darling in the FranXX starts batch four and is discoverable by its Chinese nickname', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('目录分段').selectOption('4')
  await expect(dialog.locator('.catalog-item').filter({ hasText: '50 / 50' })).toHaveCount(13)
  await expect(dialog.locator('[data-number="74"]')).toContainText('待制作')
  await dialog.getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('国家队')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('.quiz-card h3').first()).toContainText('DARLING in the FRANXX')
})

test('vinland-saga TV bank opens fifty illustrated questions on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('4')
  await expect(page.locator('.catalog-item[data-number="62"]')).toContainText('50 / 50')
  await page.getByRole('button', { name: "进入题库：Vinland Saga", exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('#exam-title')).toHaveText('冰海战记 第一季 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('电视动画第一季第 1–24 集')
  await expect(page.getByRole('dialog')).toContainText('不混入第二季')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Vinland Saga can be found by its alternative Chinese title', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('海盗战记')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await page.getByRole('button', { name: '开始：冰海战记 第一季，人物与航路入门', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('不作为真实历史知识题')
  await expect(page.getByRole('dialog')).toContainText('不混入第二季农场篇')
})

test('another TV bank opens fifty illustrated questions on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('4')
  await expect(page.locator('.catalog-item[data-number="63"]')).toContainText('50 / 50')
  await page.getByRole('button', { name: "进入题库：Another", exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('#exam-title')).toHaveText('Another 电视版 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('电视动画第 1–12 集')
  await expect(page.getByRole('dialog')).toContainText('不混入OVA')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Another exposes its mystery scope and Chinese alias', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('替身')
  await expect(page.locator('.quiz-card').filter({ hasText: 'Another 电视版' })).toHaveCount(3)
  await page.getByRole('button', { name: '开始：Another 电视版，人物与校园入门', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('不考公开简介未揭示的最终死者身份与结局机关')
})


test('demon-slayer-mugen-train opens a separate film bank on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('4')
  await expect(page.locator('.catalog-item[data-number="64"]')).toContainText('50 / 50')
  await expect(page.locator('.catalog-item[data-number="74"]')).toContainText('待制作')
  await page.getByRole('button', { name: '进入题库：Demon Slayer: Mugen Train', exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('#exam-title')).toHaveText('鬼灭之刃 无限列车篇 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('2020年剧场版')
  await expect(page.getByRole('dialog')).toContainText('不含电视版第一集原创故事')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Mugen Train is discoverable by English alias and explains its shared-story sources', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('Mugen Train')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await page.getByRole('button', { name: '开始：鬼灭之刃 无限列车篇，护卫作战与条件判断', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('共同主线参照电视版对应集简介核验')
})


test('soul-eater TV bank opens fifty illustrated questions on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('4')
  await expect(page.locator('.catalog-item[data-number="65"]')).toContainText('50 / 50')
  await expect(page.locator('.catalog-item[data-number="74"]')).toContainText('待制作')
  await page.getByRole('button', { name: '进入题库：Soul Eater', exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('#exam-title')).toHaveText('噬魂师 电视版 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 1–51 集')
  await expect(page.getByRole('dialog')).toContainText('不混入漫画差异或《噬魂师NOT!》')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Soul Eater can be found by its Chinese alias and exposes the TV scope', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('噬魂者')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await page.getByRole('button', { name: '开始：噬魂师 电视版，共鸣限制与战术判断', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('不考简介未揭示的最终制胜机制')
})


test('gurren-lagann TV bank opens fifty illustrated questions on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('4')
  await expect(page.locator('.catalog-item[data-number="66"]')).toContainText('50 / 50')
  await expect(page.locator('.catalog-item[data-number="74"]')).toContainText('待制作')
  await page.getByRole('button', { name: '进入题库：Gurren Lagann', exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('#exam-title')).toHaveText('天元突破 红莲螺岩 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 1–27 集')
  await expect(page.getByRole('dialog')).toContainText('不混入《红莲篇》《螺岩篇》')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Gurren Lagann is discoverable by its Chinese alias and states its TV scope', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('红莲之眼')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await page.getByRole('button', { name: '开始：天元突破 红莲螺岩，能力边界与宇宙战术', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('不考简介未揭示的最终制胜细节')
})


test('shield-hero season one opens fifty illustrated questions on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('4')
  await expect(page.locator('.catalog-item[data-number="67"]')).toContainText('50 / 50')
  await expect(page.locator('.catalog-item[data-number="74"]')).toContainText('待制作')
  await page.getByRole('button', { name: '进入题库：The Rising of the Shield Hero', exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('#exam-title')).toHaveText('盾之勇者成名录 第一季 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第一季第 1–25 集')
  await expect(page.getByRole('dialog')).toContainText('不混入第二季')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Shield Hero Chinese alias exposes the first-season scope', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('盾勇')
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await page.getByRole('button', { name: '开始：盾之勇者成名录 第一季，技能限制与救援判断', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('不编造技能数值')
})


test('charlotte TV bank opens fifty illustrated questions on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('4')
  await expect(page.locator('.catalog-item[data-number="68"]')).toContainText('50 / 50')
  await expect(page.locator('.catalog-item[data-number="74"]')).toContainText('待制作')
  await page.getByRole('button', { name: '进入题库：Charlotte', exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('#exam-title')).toHaveText('Charlotte 夏洛特 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第 1–13 集')
  await expect(page.getByRole('dialog')).toContainText('不混入未放送特别篇')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Charlotte Chinese alias exposes time-specific ability scope', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('夏洛特')
  await expect(page.locator('.quiz-card').filter({ hasText: 'Charlotte 夏洛特' })).toHaveCount(3)
  await page.getByRole('button', { name: '开始：Charlotte 夏洛特，发动限制与代价判断', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('能力以题目指定时点为准')
})


test('overlord season one opens fifty illustrated questions on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('4')
  await expect(page.locator('.catalog-item[data-number="69"]')).toContainText('50 / 50')
  await expect(page.locator('.catalog-item[data-number="74"]')).toContainText('待制作')
  await page.getByRole('button', { name: '进入题库：Overlord', exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('#exam-title')).toHaveText('Overlord 第一季 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第一季第 1–13 集')
  await expect(page.getByRole('dialog')).toContainText('不混入第二季')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Overlord Chinese alias exposes its first-season combat scope', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('骨王')
  await expect(page.locator('.quiz-card').filter({ hasText: 'Overlord 第一季' })).toHaveCount(3)
  await page.getByRole('button', { name: '开始：Overlord 第一季，技能条件与资源判断', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('不补写官网简介未展开的最终制胜细节')
})


test('food-wars season one opens fifty illustrated questions on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('4')
  await expect(page.locator('.catalog-item[data-number="70"]')).toContainText('50 / 50')
  await expect(page.locator('.catalog-item[data-number="74"]')).toContainText('待制作')
  await page.getByRole('button', { name: '进入题库：Food Wars!', exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('#exam-title')).toHaveText('食戟之灵 第一季 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第一季第 1–24 集')
  await expect(page.getByRole('dialog')).toContainText('不混入第二季')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Food Wars alias exposes the cooking scope and original kitchen illustration', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('药王')
  const cards = page.locator('.quiz-card').filter({ hasText: '食戟之灵 第一季' })
  await expect(cards).toHaveCount(3)
  await expect(cards.first().locator('img')).toHaveAttribute('src', /kitchen\.svg$/)
  await page.getByRole('button', { name: '开始：食戟之灵 第一季，出餐条件与选拔判断', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('不补写未核验的配方比例和正赛结局')
})


test('psycho-pass original season opens fifty illustrated questions on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('4')
  await expect(page.locator('.catalog-item[data-number="71"]')).toContainText('50 / 50')
  await expect(page.locator('.catalog-item[data-number="74"]')).toContainText('待制作')
  await page.getByRole('button', { name: '进入题库：Psycho-Pass', exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('#exam-title')).toHaveText('心理测量者 第一季 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('原版第一季第 1–22 集')
  await expect(page.getByRole('dialog')).toContainText('不混入新编集版')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Psycho-Pass Japanese alias exposes the original-season evidence scope', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('サイコパス')
  await expect(page.locator('.quiz-card').filter({ hasText: '心理测量者 第一季' })).toHaveCount(3)
  await page.getByRole('button', { name: '开始：心理测量者 第一季，读数与证据判断', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('不补写未核验的系数阈值')
})


test('entertainment district opens fifty illustrated questions on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('4')
  await expect(page.locator('.catalog-item[data-number="72"]')).toContainText('50 / 50')
  await expect(page.locator('.catalog-item[data-number="74"]')).toContainText('待制作')
  await page.getByRole('button', { name: '进入题库：Demon Slayer: Entertainment District Arc', exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('#exam-title')).toHaveText('鬼灭之刃 游郭篇 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('游郭篇第 1–11 集')
  await expect(page.getByRole('dialog')).toContainText('不混入刀匠村篇')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Entertainment District Japanese alias opens its scoped practice', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('遊郭編')
  await expect(page.locator('.quiz-card').filter({ hasText: '鬼灭之刃 游郭篇' })).toHaveCount(3)
  await page.getByRole('button', { name: '开始：鬼灭之刃 游郭篇，合击与危机推演', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('不补写简介未交代')
})


test('Mob Psycho II opens fifty illustrated questions independently on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByRole('button', { name: '查看 200 条目制作目录', exact: true }).click()
  await page.getByLabel('目录分段').selectOption('4')
  await expect(page.locator('.catalog-item[data-number="73"]')).toContainText('50 / 50')
  await expect(page.locator('.catalog-item[data-number="74"]')).toContainText('待制作')
  await page.getByRole('button', { name: '进入题库：Mob Psycho 100 II', exact: true }).click()
  await expect(page.locator('.quiz-card')).toHaveCount(3)
  await expect(page.locator('#exam-title')).toHaveText('灵能百分百 第二季 · 模拟考试')
  await page.getByRole('button', { name: '全部 50 题', exact: true }).click()
  await page.getByRole('button', { name: '生成试卷', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('第二季第 1–13 集')
  await expect(page.getByRole('dialog')).toContainText('不混入OVA或第三季')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Mob Psycho II Japanese numeral alias exposes its psychic mechanics scope', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('textbox', { name: '搜索 Quiz' }).fill('モブサイコ100Ⅱ')
  await expect(page.locator('.quiz-card').filter({ hasText: '灵能百分百 第二季' })).toHaveCount(3)
  await page.getByRole('button', { name: '开始：灵能百分百 第二季，感知与能量推演', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('不补写官网未说明的能力参数')
})
